---
title: "JA_SusieR_notes"
author: "Peter Fiorica"
date: "April 7, 2020"
output: html_document
---

```{r}
library(susieR)
library(dplyr)
library(ggplot2)
library(data.table)
library(Matrix)
library(ggrepel)
```

```
awk 'NR>=235460&&NR<=238750' 8.txt > ja_chr8_1mb_range.txt
```

```{r}
chr8dosage<-fread(sprintf('zcat %s',"/home/peter/prostate_cancer/jl_prostate_cancer/predixcan/ja_dosages/ja_chr8.txt.gz"), header = F)
chr8_gwas<-fread("/home/peter/prostate_cancer/jl_prostate_cancer/gwas/ja_chromosome_results/ja_chr8_1mb_range.txt", header = F)

combined<-left_join(chr8_gwas,chr8dosage, by=c("V2"))
combined2<-combined[!is.na(combined$V2)==T, ]

combined2$`V1.x`<-NULL
combined2[2:6]<-list(NULL)
OR_n_test<-dplyr::select(chr8_gwas, V2, V7,V8)
colnames(OR_n_test)<-c("SNP","OR", "STAT")
combined2[2:8]<-list(NULL) 
combined3<-transpose(combined2) 
susier_geno<-combined3

fwrite(susier_geno, "/home/peter/prostate_cancer/jl_prostate_cancer/jl_susier_input.txt", col.names = F , row.names = F, sep = " ", quote= F)

fwrite(OR_n_test, "/home/peter/prostate_cancer/jl_prostate_cancer/jl_chr8_ORnTEST.txt", col.names = T, row.names = F, sep = " ", quote= F)
```


```{r, cache = TRUE}
susier_geno <- fread("Z://prostate_cancer/jl_prostate_cancer/jl_susier_input.txt", header = T) #This just reads in the file we wrote.

OR_chr_8<-fread("Z://prostate_cancer/jl_prostate_cancer/jl_chr8_ORnTEST.txt", header = T)

phenotypes<-fread("Z://prostate_cancer/jl_prostate_cancer/jl_residual_phenotypes.txt", header = T)

susier_matrix<-as.data.table(susier_geno)
susier_matrix<-as.matrix(susier_matrix)
susier_matrix<-Matrix(susier_matrix, sparse=T)

fitted <- susie(susier_matrix, phenotypes$Pheno,
                L = 10,
                estimate_residual_variance = TRUE, 
                estimate_prior_variance = FALSE,
                scaled_prior_variance = 0.1,
                verbose = TRUE)

confidence<-fitted$sets
print(fitted$sets)
susie_plot(fitted, y= "PIP") + title("CHR 8: 127367233 - 129069027")

zscore<-data.table(OR_chr_8,fitted$pip)
colnames(zscore)<-c("SNP" ,"OR",   "STAT", "PIP" )
zscore$abs<-abs(zscore$STAT)
```