---
title: "Figure2"
author: "Peter Fiorica"
date: "May 12, 2020"
output: html_document
---

```{r, warning=FALSE}
library(dplyr)
library(data.table)
library(ggplot2)
library(stringr)
library(gridExtra)
library(ggrepel)
```

#Introduction
These notes comment on the code used to generate Figure 2 for our prostate cancer paper.


# Read in Files to be Used
```{r}
ja_pred<-fread("Z://prostate_cancer/jl_prostate_cancer/predixcan/japnese_american_gtex8_male_tissues_lfsr_manhattan.txt", header = T, stringsAsFactors = T)

ja_pred$CHR<-ifelse(ja_pred$genename=="FAM227A", "22", ja_pred$CHR)
ja_pred$BP<-ifelse(ja_pred$genename=="FAM227A", "38578120", ja_pred$BP)
ja_pred$CHR<-as.numeric(ja_pred$CHR)
ja_pred$BP<-as.numeric(ja_pred$BP)

aa_pred<-fread("Z://prostate_cancer/predixcan/aa_gtex8_predixcan_4manplot.txt", header = T, stringsAsFactors = T)
```



# Manhattan Plot 1 (AfAm)
```{r}
manhattantotal4plot<-aa_pred
don <- manhattantotal4plot %>%
  # Compute chromosome size
  group_by(CHR) %>% 
  summarise(chr_len=max(BP)) %>%
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(manhattantotal4plot, ., by=c("CHR"="CHR")) %>%
  arrange(CHR, BP) %>%
  mutate( BPcum=BP+tot)

axisdf = don %>% group_by(CHR) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

axisdf<- axisdf[!is.na(axisdf$CHR),]
don$lfsr<-don$ash_halfuni_pX

manplot8_aa<-ggplot(don, aes(x=BPcum, y=-log10(p), size = (lfsr))) +
# Show all points
geom_point(aes(color=as.factor(CHR)), alpha=0.3, na.rm = T) +
scale_color_manual(values = rep(c("#619CFF", "sandybrown", "#00BA38", "#F8766D"), 22 )) +

# custom X axis:
scale_x_continuous( label = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18," ", 20, " ", 22), breaks= axisdf$center, expand = c(0,0) ) +
scale_y_continuous(expand = c(0, 0), limits = c(0,8) ) +     # remove space between plot area and x axis
# Custom the theme:
theme_bw(16) +
xlab("Chromosome") + ylab(expression(paste("-log"[10],"(P)"))) + ggtitle("A") +
  guides(colour=F)+
theme(panel.grid.major.x = element_blank(),
panel.grid.minor.x = element_blank(),
panel.grid.major.y = element_blank(),
panel.grid.minor.y = element_blank()
) +scale_size_continuous(name= "lfsr", breaks=c(0.5,0.25,0.1,0.05), range=c(10,1))+ facet_wrap(~"African American GTEx version 8", nrow=1)
# PrediXcan Line
# geom_hline(yintercept = -log10(0.05/489146), color= "red")
```


# Manhattan Plot 2
```{r}
manhattantotal4plot<-ja_pred

ja_don <- manhattantotal4plot %>%
  # Compute chromosome size
  group_by(CHR) %>% 
  summarise(chr_len=max(BP)) %>%
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(manhattantotal4plot, ., by=c("CHR"="CHR")) %>%
  arrange(CHR, BP) %>%
  mutate( BPcum=BP+tot)

axisdf = ja_don %>% group_by(CHR) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

axisdf<- axisdf[!is.na(axisdf$CHR),]
ja_don$lfsr<-ja_don$ash_halfuni_pX

manplot8_ja<-ggplot(ja_don, aes(x=BPcum, y=-log10(p), size = (lfsr))) +
# Show all points
geom_point(aes(color=as.factor(CHR)), alpha=0.3, na.rm = T) +
scale_color_manual(values = rep(c("#619CFF", "sandybrown", "#00BA38", "#F8766D"), 22 )) +

# custom X axis:
scale_x_continuous( label = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18," ", 20, " ", 22), breaks= axisdf$center, expand = c(0,0) ) +
scale_y_continuous(expand = c(0, 0), limits = c(0,8) ) +     # remove space between plot area and x axis
# Custom the theme:
theme_bw(16) +
xlab("Chromosome") + ylab(expression(paste("-log"[10],"(P)"))) + ggtitle("B") +
  guides(colour=F)+
theme(panel.grid.major.x = element_blank(),
panel.grid.minor.x = element_blank(),
panel.grid.major.y = element_blank(),
panel.grid.minor.y = element_blank()
) +scale_size_continuous(name= "lfsr", breaks=c(0.5,0.25,0.1,0.05), range=c(10,1))+ facet_wrap(~"Japanese American GTEx version 8", nrow=1)
# PrediXcan Line
# +geom_hline(yintercept = -log10(0.05/646847146), color= "red")
```


```{r}
grid.arrange(grobs=list(manplot8_aa, manplot8_ja), nrow = 1, ncol = 2)
```